### ISSUE TITLE
[water-wave] 모바일 버전 구현

### ISSUE THREAD

**Issue by ovoHJ** [MaetDol/JSToys#34]
물살이라도..!

**Comment by MaetDol** [comment]
물살.. 어떤거였쬬.. 가물가물...

**Comment by MaetDol** [comment]
스마트폰 기울이면 수면도 같이 기울어지게 작업하기..

**Comment by MaetDol** [comment]
일단 모바일 환경에서 구동은 되는 듯 하니, 이슈를 닫겠습니다!
추가적인 기능 추가나, 변경사항이 필요하다 생각하신다면 해당 이슈를 리오픈해주시거나 새로 만들어주세요!
